{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $podTemplate := .Values.restapi.podTemplate -}}
{{- $labels := fromYaml (include "slurm.labels" $) -}}
{{- $metadata := merge (dict "labels" $labels) ($podTemplate.metadata | default dict) -}}
{{- $_ := set $podTemplate "metadata" $metadata -}}
{{- $imagePullSecrets := concat ($podTemplate.imagePullSecrets | default list) (.Values.imagePullSecrets | default list) -}}
{{- $_ := set $podTemplate "imagePullSecrets" $imagePullSecrets -}}
{{- $priorityClassName := $podTemplate.priorityClassName | default .Values.priorityClassName -}}
{{- $_ := set $podTemplate "priorityClassName" $priorityClassName -}}
apiVersion: slinky.slurm.net/v1alpha1
kind: RestApi
metadata:
  name: {{ include "slurm.fullname" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  controllerRef:
    name: {{ include "slurm.fullname" . }}
    namespace: {{ include "slurm.namespace" . }}
  {{- with .Values.restapi.replicas }}
  replicas: {{ . }}
  {{- end }}{{- /* with .Values.restapi.replicas */}}
  {{- with .Values.restapi.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with .Values.restapi.service */}}
  template:
    {{- include "format-podTemplate" $podTemplate | nindent 4 }}
    slurmrestd:
      {{- include "format-container" .Values.restapi.slurmrestd | nindent 6 }}
