{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.operator.enabled }}
{{- if .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "slurm-operator.operator.serviceAccountName" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "slurm-operator.operator.serviceAccountName" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slinky.slurm.net
  resources:
  - accountings
  - controllers
  - loginsets
  - nodesets
  - restapis
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slinky.slurm.net
  resources:
  - accountings/finalizers
  - controllers/finalizers
  - loginsets/finalizers
  - nodesets/finalizers
  - restapis/finalizers
  - tokens/finalizers
  verbs:
  - update
- apiGroups:
  - slinky.slurm.net
  resources:
  - accountings/status
  - controllers/status
  - loginsets/status
  - nodesets/status
  - restapis/status
  - tokens/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "slurm-operator.operator.serviceAccountName" . }}
  labels:
    {{- include "slurm-operator.operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "slurm-operator.operator.serviceAccountName" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "slurm-operator.operator.serviceAccountName" . }}
{{- end }}{{- /* if .Values.operator.serviceAccount.create */}}
{{- end }}{{- /* if .Values.operator.enabled */}}
