{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.operator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm-operator.name" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.operator.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "slurm-operator.operator.labels" . | nindent 4 }}
  ports:
    {{- if ne (int .Values.operator.metricsPort) 0 }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.operator.metricsPort | default 8080 }}
      targetPort: {{ .Values.operator.metricsPort | default 8080 }}
    {{- end }}{{- /* if .Values.operator.metricsPort != 0 */}}
    - name: health
      protocol: TCP
      port: {{ .Values.operator.healthPort | default 8081 }}
      targetPort: {{ .Values.operator.healthPort | default 8081 }}
{{- end }}{{- /* if .Values.operator.enabled */}}
