{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- range $key, $nodeset := $.Values.nodesets -}}
{{- if $nodeset.enabled }}
{{- $name := printf "%s-%s" (include "slurm.compute.name" $) $key }}
{{- $podTemplate := $nodeset.podTemplate -}}
{{- $labels := fromYaml (include "slurm.labels" $) -}}
{{- $labels = merge $labels (dict "nodeset.slinky.slurm.net/name" $name) -}}
{{- $metadata := merge (dict "labels" $labels) ($podTemplate.metadata | default dict) -}}
{{- $_ := set $podTemplate "metadata" $metadata -}}
{{- $imagePullSecrets := concat list ($podTemplate.imagePullSecrets | default list) ($.Values.imagePullSecrets | default list) -}}
{{- $_ := set $podTemplate "imagePullSecrets" $imagePullSecrets -}}
{{- $priorityClassName := $podTemplate.priorityClassName | default $.Values.priorityClassName -}}
{{- $_ := set $podTemplate "priorityClassName" $priorityClassName -}}
{{- if $nodeset.useResourceLimits }}
  {{- $envLimts := list (dict "name" "POD_CPUS" "value" (include "slurm.compute.podCpus" $nodeset.slurmd | toString)) (dict "name" "POD_MEMORY" "value" (include "slurm.compute.podMemory" $nodeset.slurmd | toString)) -}}
  {{- $slurmdEnv := concat list ($nodeset.slurmd.env | default list) $envLimts -}}
  {{- $_ := set $nodeset.slurmd "env" $slurmdEnv -}}
{{- end }}{{- /* if $nodeset.useResourceLimits */}}
{{- if (include "slurm.compute.extraConf" $nodeset) }}
  {{- $_ := set $podTemplate "extraConf" (include "slurm.compute.extraConf" $nodeset) -}}
{{- end -}}{{- /* if (include "slurm.compute.extraConf" $nodeset) */}}
---
apiVersion: slinky.slurm.net/v1alpha1
kind: NodeSet
metadata:
  name: {{ $name }}
  namespace: {{ include "slurm.namespace" $ }}
  labels:
    nodeset.slinky.slurm.net/name: {{ $name }}
    {{- include "slurm.labels" $ | nindent 4 }}
spec:
  controllerRef:
    name: {{ include "slurm.fullname" $ }}
    namespace: {{ include "slurm.namespace" $ }}
  {{- with $nodeset.partition }}
  partition:
    enabled: {{ $nodeset.enabled | default false }}
    {{- if (include "slurm.compute.PartitionConfig" $nodeset.partition) }}
    config: {{ include "slurm.compute.PartitionConfig" $nodeset.partition }}
    {{- end }}{{- /* if (include "slurm.compute.PartitionConfig" $nodeset.partition) */}}
  {{- end }}{{- /* with $nodeset.partition */}}
  replicas: {{ $nodeset.replicas }}
  template:
    {{- include "format-podTemplate" $podTemplate | nindent 4 }}
    hostname: "{{ $key }}-"
    slurmd:
      {{- include "format-container" $nodeset.slurmd | nindent 6 }}
    logfile:
      {{- include "format-container" $nodeset.logfile | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
{{- end }}{{- /* $nodeset.enabled */}}
{{- end }}{{- /* range $nodeset := $.Values.nodesets */}}
