{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- range $key, $loginset := $.Values.loginsets }}
{{- if and $.Values.networkPolicy.enabled $loginset.enabled (dig "networkPolicy" "enabled" true $loginset) }}
{{- $name := printf "%s-%s" (include "slurm.login.name" $) $key }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}
  namespace: {{ include "slurm.namespace" $ }}
  labels:
    {{- include "slurm.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: login
      app.kubernetes.io/instance: {{ $name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 22
    {{- with $.Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "networkPolicy" "extraIngress" nil $loginset) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - ports:
        - protocol: TCP
          port: {{ include "slurm.controller.port" $ }}
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: slurmctld
    - ports:
        - protocol: TCP
          port: 22
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: slurmd
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- with $.Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (dig "networkPolicy" "extraEgress" nil $loginset) }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
