{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.nodeset }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "slurm.fullname" . }}-nodeset
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: slurmd
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ include "slurm.worker.port" . }}
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: slurmctld
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: slurmd
    {{- $sshEnabled := false }}
    {{- range $key, $nodeset := .Values.nodesets }}
      {{- if and $nodeset.enabled (dig "ssh" "enabled" false $nodeset) }}
        {{- $sshEnabled = true }}
      {{- end }}
    {{- end }}
    {{- if $sshEnabled }}
    - ports:
        - protocol: TCP
          port: 22
      from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: login
    {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - ports:
        - protocol: TCP
          port: {{ include "slurm.controller.port" . }}
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: slurmctld
    - ports:
        - protocol: TCP
          port: {{ include "slurm.worker.port" . }}
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: slurmd
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
