{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slurm-operator.webhook.name" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "slurm-operator.webhook.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9443
    {{- if ne (int .Values.webhook.metricsPort) 0 }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.webhook.metricsPort | default 8080 }}
      targetPort: {{ .Values.webhook.metricsPort | default 8080 }}
    {{- end }}{{- /* if .Values.webhook.metricsPort != 0 */}}
    - name: health
      protocol: TCP
      port: {{ .Values.webhook.healthPort | default 8081 }}
      targetPort: {{ .Values.webhook.healthPort | default 8081 }}
{{- end }}{{- /* if .Values.webhook.enabled */}}
