---
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta13
kind: Config
deploy:
  helm:
    releases:
      - name: slurm-operator-crds
        chartPath: ./
        skipBuildDependencies: true
