{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.accounting.enabled }}
{{- $podTemplate := .Values.accounting.podTemplate -}}
{{- $labels := fromYaml (include "slurm.labels" $) -}}
{{- $metadata := merge (dict "labels" $labels) ($podTemplate.metadata | default dict) -}}
{{- $_ := set $podTemplate "metadata" $metadata -}}
{{- $imagePullSecrets := concat list ($podTemplate.imagePullSecrets | default list) (.Values.imagePullSecrets | default list) -}}
{{- $_ := set $podTemplate "imagePullSecrets" $imagePullSecrets -}}
{{- $priorityClassName := $podTemplate.priorityClassName | default .Values.priorityClassName -}}
{{- $_ := set $podTemplate "priorityClassName" $priorityClassName -}}
apiVersion: slinky.slurm.net/v1alpha1
kind: Accounting
metadata:
  name: {{ include "slurm.fullname" . }}
  namespace: {{ include "slurm.namespace" . }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
spec:
  slurmKeyRef:
    {{- if .Values.slurmKeyRef }}
    {{- toYaml .Values.slurmKeyRef | nindent 4 }}
    {{- else }}
    name: {{ include "slurm.authSlurmRef.name" . }}
    key: {{ include "slurm.authSlurmRef.key" . }}
    {{- end }}{{- /* if .Values.slurmKeyRef */}}
  jwtHs256KeyRef:
    {{- if .Values.jwtHs256KeyRef }}
    {{- toYaml .Values.jwtHs256KeyRef | nindent 4 }}
    {{- else }}
    name: {{ include "slurm.authJwtHs256Ref.name" . }}
    key: {{ include "slurm.authJwtHs256Ref.key" . }}
    {{- end }}{{- /* if .Values.jwtHs256KeyRef */}}
  {{- if (include "slurm.accounting.extraConf" .) }}
  extraConf: |
    {{- include "slurm.accounting.extraConf" . | nindent 4 }}
  {{- end }}{{- /* if (include "slurm.accounting.extraConf" .) */}}
  template:
    {{- include "format-podTemplate" $podTemplate | nindent 4 }}
    slurmdbd:
      {{- include "format-container" .Values.accounting.slurmdbd | nindent 6 }}
    initconf:
      {{- include "format-container" .Values.accounting.initconf | nindent 6 }}
  {{- with .Values.accounting.storageConfig }}
  storageConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}{{- /* with .Values.accounting.storageConfig */}}
{{- end }}{{- /* if .Values.accounting.enabled */}}
