---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slinky.slurm.net
  resources:
  - accountings
  - controllers
  - loginsets
  - nodesets
  - restapis
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slinky.slurm.net
  resources:
  - accountings/finalizers
  - controllers/finalizers
  - loginsets/finalizers
  - nodesets/finalizers
  - restapis/finalizers
  - tokens/finalizers
  verbs:
  - update
- apiGroups:
  - slinky.slurm.net
  resources:
  - accountings/status
  - controllers/status
  - loginsets/status
  - nodesets/status
  - restapis/status
  - tokens/status
  verbs:
  - get
  - patch
  - update
