---
apiVersion: v2
kubeVersion: ">= 1.29.0-0"

name: slurm-operator
description: Slurm Operator
type: application
appVersion: "25.05"
version: 0.4.0

annotations:
  license: Apache-2.0

home: https://slinky.schedmd.com/
icon: https://github.com/SlinkyProject/docs/blob/main/docs/_static/images/slinky.svg

sources:
  - https://github.com/SlinkyProject/slurm-operator

maintainers:
  - name: SchedMD LLC.
    email: slinky@schedmd.com
    url: https://support.schedmd.com/

dependencies:
  - name: slurm-operator-crds
    version: "0.4.0"
    condition: crds.enabled
    repository: file://../slurm-operator-crds
