---
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v4beta11
kind: Config
profiles:
  - name: dev
    build:
      artifacts:
        # substitute the image repository with your own
        - image: slinky.slurm.net/slurm-operator
          runtimeType: go
          context: ../../
          docker:
            dockerfile: Dockerfile.dev
          hooks:
            before:
              - command: ["make", "vendor"]
                dir: ../../
                os: [linux, darwin]
      tagPolicy:
        inputDigest: {}
      local:
        # only push the image if the current Kubernetes context connects to a remote cluster
        push: false
        # in certain cases you may need this to authenticate with your registry
        # useDockerCLI: true
    deploy:
      helm:
        releases:
          - name: slurm-operator
            chartPath: ./
            valuesFiles:
              - ./values-dev.yaml
            setValueTemplates:
              image.repository: '{{.IMAGE_REPO}}'
              image.tag: '{{.IMAGE_TAG}}'
            namespace: slinky
            createNamespace: true
deploy:
  helm:
    releases:
      - name: slurm-operator
        chartPath: ./
        valuesFiles:
          - ./values-dev.yaml
        namespace: slinky
        createNamespace: true
