{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.networkPolicy.enabled .Values.operator.enabled .Values.operator.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "slurm-operator.name" . }}
  namespace: {{ include "slurm-operator.namespace" . }}
  labels:
    {{- include "slurm-operator.operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "slurm-operator.operator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if ne (int .Values.operator.metricsPort) 0 }}
    - ports:
        - protocol: TCP
          port: {{ .Values.operator.metricsPort | default 8080 }}
    {{- end }}
    {{- with .Values.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.operator.networkPolicy.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    - ports:
        - protocol: TCP
          port: 443
    - ports:
        - protocol: TCP
          port: 6820
      to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: slurmrestd
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.operator.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
