rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
      - persistentvolumeclaims
      - pods
      - secrets
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
      - deployments
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - patch
      - update
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - slinky.slurm.net
    resources:
      - accountings
      - accounts
      - controllers
      - loginsets
      - nodesets
      - restapis
      - tokens
      - users
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - slinky.slurm.net
    resources:
      - accountings/finalizers
      - accounts/finalizers
      - controllers/finalizers
      - loginsets/finalizers
      - nodesets/finalizers
      - restapis/finalizers
      - tokens/finalizers
      - users/finalizers
    verbs:
      - update
  - apiGroups:
      - slinky.slurm.net
    resources:
      - accountings/status
      - accounts/status
      - controllers/status
      - loginsets/status
      - nodesets/status
      - restapis/status
      - tokens/status
      - users/status
    verbs:
      - get
      - patch
      - update
